#!/bin/bash

# exit when any command fails
set -e

# requires: circom file (e.g. battleship.circom)

circom $@
#snarkjs printconstraints
snarkjs info
snarkjs setup --protocol groth
snarkjs generateverifier

# output: circuit.json, proving_key.json, verification_key.json, verifier.sol
