#!/bin/bash

# exit when any command fails
set -e

# requires: circuit.json, input.json, proving.key

snarkjs calculatewitness
snarkjs proof
rm -f witness.json
snarkjs verify	# test the proof by verifying it

# output: proof.json, public.json
